on:
  push:
    branches:
      - dist
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 23.5

      - name: Install Dependencies
        run: npm install

      - name: Expose API Token
        run: echo "VITE_GITHUB_TOKEN=${{ secrets.GH_PAT }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Nojekyll
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
