on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Node Setup
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 23.5

      - name: Install Dependencies
        run: npm install

      - name: Expose API Token
        run: echo "VITE_GITHUB_TOKEN=${{ secrets.GH_PAT }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
